apiVersion: 1

deleteDatasources:
  - name: Grafana React SDK POC TestData
    orgId: 1

datasources:
  - name: Grafana React SDK POC TestData
    uid: grsdk-testdata
    type: grafana-testdata-datasource
    access: proxy
    orgId: 1
    isDefault: true
    editable: false
